# Title: corrections.py
# Brief: setting up base operation to forward RTCM correction from GPS UART2 to the radio
#        Will also be listening out to incoming data from the radio - messages from the rover
#        Will probably be linked to Message.py
# Author: Sherif Attia
# Date: 15/07/2022


# RTCM messages are generated by the base
class Corrections:
    def __init__(self, message):
        # init setup
        self.message = message

